### ISSUE TITLE
Translation error in about.tpl

### ISSUE THREAD

**Issue by jucdn** [butterproject/butter-desktop#112]
Because of an inconsistency in [butter-desktop/src/app/templates/about.tpl](https://github.com/butterproject/butter-desktop/blob/131180d31d599792c8aa21b97b4dc624125eacb1/src/app/templates/about.tpl#L21)  with the space before "!" in the first sentence of the page, this part isn't translated by i18n.

**Comment by insertc0in** [comment]
Thanks for mentioning this.
Actually the problem is that the translation files don't literally match what's in the code now.
Also the exclamation mark is absolutely pointless. I PR'd the needed changes:
https://github.com/insertc0in/butter-desktop/commit/0fee09368bcbe84f4aaca444949df9e563534e02
https://github.com/butterproject/butter-desktop/commit/e40fcb3f732fb166de2af15b0455057fbe737942
