### ISSUE TITLE
Remove torrent search.

### ISSUE THREAD

**Issue by matthewbauer** [butterproject/butter-desktop#24]
Under the torrent adding there is the ability to search on Kick Ass Torrents and Strike. To maintain 100% legality status we should probably remove it. Otherwise I think it is still illegal in the states under the "[inducement rule](https://en.wikipedia.org/wiki/Inducement_rule)".

**Comment by paulhobbel** [comment]
But i think there should be a option to enable it or atleast some files you can add to let it work again

**Comment by hadim** [comment]
- The option should me kept. 
- KAT and Strike should be removed.
- This feature should work with a plugin system.

Just my toughs on it

**Comment by kirashi3** [comment]
@matthewbauer has the right idea removing the ability to search for certain content out of the box, but I know you would be safe legally if you simply left it open as a "write your own plugin" system.

I feel it should be treated the same way Kodi (XBMC) has been doing it for years: a plugin system, as @hadim mentioned. People have been writing plugins for Kodi for as long as I can remember since its' early releases that allow you to acquire questionable content.

Having an open system simply says "Here's the framework, you may do what you will with it" similar to a realtor selling a house to someone who later turns it into a drug shop. Yes, it's illegal, and a bit extreme of an example, but my point is that who would arrest the realtor for this?

**Comment by hadim** [comment]
The awesome feature would be a plugin system distributed bia P2P !!!

**Comment by TheAtomicGoose** [comment]
FWIW, this feature isn't working for me anyway. I don't know if it's a problem specific to me, but when I try to play something found through the KAT search feature, it hangs on "Connecting".

**Comment by douglascamata** [comment]
This feature can be replaced with a simple "Open torrent from magnet link"... what you think? And we can also keep the drag 'n' drop torrent feature. Would there be any legal issues with this?

**Comment by felipecaputo** [comment]
Maybe something like the Chrome config for search engines, where you register the url and them it search using the previous configured search, them you won't need a plugin

**Comment by matthewbauer** [comment]
I suppose that would work. Although if the drag and drop still works why can't users just visit kat.cr, search for content, then drag the link to butter. I'm not against implementing some sort of search plugin system I just think the benefit of a feature like that is not so useful.

**Comment by her** [comment]
Removing the search but having an extension or plugin seems like a sensible solution

**Comment by healiha** [comment]
@douglascamata and @matthewbauer be it magnet link or drag 'n' drop, both are available in all major torrent client. I don't see any point in removing those features and I doubt there would be any legal issues.

As for the search engines, I agree with @hadim, the best thing to do would be removing KAT and Strike and add a plugin system. Once again, no legal issues here as Butter would be provided "as is/as it is" and let people alter his functionalities if they want by creating a plugin to match their own needs.

**Comment by Fabricio20** [comment]
There should be a special protocol like butter:<torrent id> so when clicking on that links we can get to stream it directly on butter (Like magnets).

Also keeping the drag 'n' drop feature is essential.

**Comment by pepijn809** [comment]
A plugin system could definitly work out, this works out for KODI, so why not here? 
I do worry, if the framework allows for KAT search, should it only allow search plugins to be made, or much more?

Because, i would not mind a search plugin, but a plugin that does exactly what the TV section showed in Popcorn Time did would be to far, as for legal stand point, right?

Even if Butter isn't the one creating it, they may also not be the one removing it. 
I guess it's something to take in consideration when deciding to or not to build this framework, and what will be "Officially" allowed to be added on it?

**Comment by Draxler** [comment]
However, Drag and Drop feature and feature to add magnet links and .torrents doesn't hurt the legality of this app, since .torrent's and magnet links serves for legal content as well. This feature would not in any way conflict with legal point view.. I understnad that Search engines such as KAT and Strike could contradict legality of this app if stay as part of the Butter so i understand these 2 shouldn't inergrated into app its self. But feaures menchen above do not and it should stay as part of Butter. That's why uTorrent and other torrent clients still exist today, because they are not offering any content at all, so no one could say nothing about infringement on their part. People use torrents and magnet links for legal stuff as well. In the end, the users are the ones who chooes what material they want to get with their clients. So i realy hope ''Drag and Drop feature'' and ''feature to add magnet links and .torrents'' will stay as part of Butter features.

**Comment by pepijn809** [comment]
@Draxler Hey man! How are you? ;)

I totally agree, and i think this may already have been confirmed, that drag and drop magnet will not be removed. From legal standpoints it makes perfect sense. 

KAT search and possible other plugins may indeed contradict the legality of Butter. I think doubt if anyone can prove the features are aimed "piracy" but there is the possibility of creating that associated picture with Butter. Kodi has had the recent press about there addon system, which is also really aimed at the amount of plugins that offer pirated content. Due Butters connection to Popcorn Time, this may be an even bigger issue.

But then again, a framework could also be harmless, if done properly.

**Comment by Draxler** [comment]
@pepijn809

I'm fine, thanks :-)   (however, not to happy how all this Popcorn Time story ''end'', which also litlle remind me of ''another story'' but that's life i gues)  :-) 

If Butter would be striped of all torrent engines and offers only Public Domains material and other free content, then, i don't think asociation with late Popcorn Time project could hurt this project in any way if plugin feature would be included as part of Butter ... 
When user buy TV...  TV company can't be resposible when user choose to ''plugin'' DVD/BD player into TV and watch copyright protected content on that TV trough DVD/BD player. 
Butter also can't be resposible in anyway what plugins are conected to Butter.

**Comment by fonix232** [comment]
I agree that a plugin system would NOT be legally challenging in any way. Kodi/XBMC and Plex has a quite wide-range plugin system, which basically allows content providing plugins from various sources - let it be a local SMB file storage, a custom streaming implementation, or pretty much anything else, including custom torrent search engines.

Of course Butter does not have to bundle any of these plugins, or even provide an official repository - simply provide a way to add plugins (e.g. directly from GitHub or from local folders). That way all responsibility can be dismissed about usage (after all, MS is not responsible for e.g. child porn traffickers sending Word docx files filled with their "collection" pictures).

**Comment by paulhobbel** [comment]
This is a todo i guess they will first release some sort of alpha version, after that the plugins will come

**Comment by pepijn809** [comment]
@paulhobbel  Of course, it's all "future features" talk ;)

I guess there are advantages and possible disadvantages to such frameworks. I don't oppose a well written framework for plugins in any way. 
But honestly, i am already satisfied with the magnet support. I wonder what the future will bring, if this plugin idea can actually take off, because at Popcorn Time they always talked about modularity, and a simple plugin framework would do that trick, right? 

Since i'm no experienced coder, how long would it take? Anybody with expierience that can answer this? Just an estimation.

**Comment by fonix232** [comment]
@pepijn809 it depends on what this plugin system is supposed to support. For our purpose, it should contain option for multiple types: search provider plugins (for finding movies, shows, etc.), source provider plugins (for streaming from various sources), and so on.

**Comment by rom1504** [comment]
This issue is now required for anybody to be able to do a npm install, kat-api was deleted https://www.npmjs.com/package/kat-api https://github.com/butterproject/butter-desktop/blob/master/package.json#L41

**Comment by paulhobbel** [comment]
Tell me if the kat api is still required, if so i can push it to github

**Comment by wb9688** [comment]
Yeah, it should be with a plugin system like in the [Pulsar plugin](https://github.com/steeve/plugin.video.pulsar) for Kodi

**Comment by sergiomb2** [comment]
Hello , IMO , to be legal , doesn't mean that should block torrent search of KAT , it means that shouldn't bundle it , but should allow user configure his search engines  and his providers etc , I thought that is what is happened. 
Like Azureus for example
