### ISSUE TITLE
Limiting download/upload speed

### ISSUE THREAD

**Issue by YIFYtorrents** [butterproject/butter-desktop#245]
I am planning to code a function to limit down/up speed for the new  [v3.9](http://github.com/PopcornTime-CE) on [/r/PopcornTimeCE](http://reddit.com/r/PopcornTimeCE). My question is weather it would be a difficult task or not? Do I have to edit `/node_modules/peerflix/index.js` or `/node_modules/peerflix/app.js` or is it enough to modify [src/app/lib/streamer.js](https://github.com/butterproject/butter-desktop/blob/master/src/app/lib/streamer.js) ?

**Comment by vankasteelj** [comment]
It would be very difficult to my knowledge. You'll need to work with torrent-stream directly, or even deeper, and throttle network activity at the very beginning. 

It might be achieved by setting some fixed ports and use only those when activating the "limited" speed option, I guess. Maybe throttle-proxy has some things to deliver, I don't know.

But as far as I can tell, it's not easy, it's a peerflix todo-list since forever, and the lack of it done today probably means it really is difficult.

**Comment by YIFYtorrents** [comment]
The problem is that people with slow internet connection or on a WIFi, could flood the network. Why can't we have an option dynamiclly change the speed every second. I mean going up and down. The current speed is continues (static) and acts like a car.

**Comment by kuboosoft** [comment]
mmm maybe change the //Ratio in "settings.js"
