### ISSUE TITLE
Someone really needs to look at the Travis CI

### ISSUE THREAD

**Issue by jamesyc** [butterproject/butter-desktop#288]
https://travis-ci.org/butterproject/butter-desktop/builds

Does anyone here actually bother to check if your builds pass CI and stuff? What's the point of using Travis CI if you're just going to ignore it? 

Also, node 0.10.x, really? What is this, 2013? It'd be great if someone could figure out what needs to be patched to get everything running on Node 4.x LTS

**Comment by vankasteelj** [comment]
I'm working locally with node 5.x and I've never encountered any issue with Butter. Update could be done without issue IMO. But it might be good to try and keep 0.10 as a requirement, for people might be stuck with older NodeJS versions (because of old habits, company guidelines, or w/e).

**Comment by xaiki** [comment]
we actually need tests, currently travis doesn't bring us any usueful info at all..

**Comment by jamesyc** [comment]
Updating from node .10 should be better, it's really old now. 

Travis is failing right now, even without tests, so somebody should figure out all of the mess.

**Comment by vankasteelj** [comment]
No, it's not really. 

CI is failing because of jshint, which is only there for readability and efficiency, it doesn't mean "butter doesn't work", it means "we implemented a strict code verification on butter and passing that test fails so CI never actually gets to try and build the app".

Node 0.10 is a LTS support, it's not deprecated, it's just old. Again, updating _could_ be done, but it's not a requirement.

As for dependencies, only `moment` should be updated asap, as it contains a security issue (regex denial of service), the other are only "not up to date", but aren't mandatory updates. Most of them aren't even patches, they're just new backward-compatible features, and we don't have a need for these features. So yes, updating the deps _could_ be done, but isn't needed either (except for `moment`)

There's a PR right now in queue to fix failing JShint, and I'll update `moment` once that PR is merged (not to introduce possible merging issues in case `moment` doesn't follow semver and minor update are in fact not backward compatible).

**Comment by jamesyc** [comment]
Well, obviously you can run the project without Travis ever compiling, but that's... missing the point of Travis (being there right under the name, on the README.md page), isn't it? It's a useful tool that's basically left to rot.

I didn't say node v.10 is deprecated, but it's kinda like running Windows Vista right now. Both are old tools in extended/LTS support and upgrading to the next LTS version is advisable at this point. Better now than after support is completely dropped. 

Glad that the JShint fix is in the works, though.

**Comment by vankasteelj** [comment]
mmmmh, we do have moment 2.11.2 as we're fetching 2.x.x, idk why the dependency thing is mad.

**Comment by vankasteelj** [comment]
ok, everything works now. I'm leaving this open for 2 reasons:
- node (I still think we don't need to update)
- travis CI passing but not building packages (see log for details)

**Comment by xaiki** [comment]
on the longrun we're going to want to make a switch to electron (better mantained, clearer interfaces, ui/workers threads separation).
but before that happens we need a few things to happen:
 - integrate wcjs
   - i feel the best way is to make a videojs tech
 - change our view layer to use react (so we can test the ui without it breaking on us).

**Comment by jamesyc** [comment]
Moving off of Node v0.10 is a good idea if you consider how soon it will be EOL'd. 

https://github.com/nodejs/LTS  
https://github.com/nodejs/LTS/blob/master/schedule.png  

As of today, you have 7 months and 5 days before it's completely unsupported. You probably don't want to move off of Node v.10 the day before it drops support, too, so you want to start earlier.

**Comment by vankasteelj** [comment]
So, as I moved grunt to gulp, I also used that opportunity to upgrade to nodejs 4 and npm 3 on travis. I made it check for `tests` (css compilation and jshint) and `build` (nw-builder). 

That being said, @xaiki thinks there's a possibility of using travis to make it build our redistribuable packages (and upload them somewhere). So that's be a good thing to do.

**Comment by vankasteelj** [comment]
closing this as duplicate, the other issue linked above will serve as main topic, now that we moved to gulp/node>4/travis
