### ISSUE TITLE
Remove issue.js

### ISSUE THREAD

**Issue by ZakariaRidouh** [butterproject/butter-desktop#368]
Was wondering about everyone's opinions about removing issue.js so we don't have to have the gitlab dependency. Also seeing that Github has a good issue management system I feel we dont need Issue.JS anymore.

related to #354

**Comment by vankasteelj** [comment]
`issue.js` used the gitlab API to post new issues from the app to gitlab. The same can be achieved with github, allowing people to report bugs in the github issue tracker without having to leave the application. 

I don't think we at butter have a use for that, but it _could_ be of use to forks. The issue is that the code as it is now has 2 flaws:

1. It's written pretty poorly, all embed in one html/js/css file, without even using the framework (which does make it portable, but also make it hard to maintain and not very pretty code-wise)
2. it uses gitlab, where it should support gitlab/github/jira (and at least github) in order to be interresting.

Now, the other thing is: should we delete code _only_ because _we_ don't have a use for it? If it's needed at one point, by us or a fork, we might regret not having it anymore.

ping @xaiki and @streger

**Comment by streger** [comment]
I agree with you @vankasteelj we don't need it (hope we don't use, because of experience before). But i'm also not for deletion, maybe comment out or put in some branch or even put it in gist.

**Comment by ZakariaRidouh** [comment]
@streger Correct, I think that it should be commented out so that if we ever need it or if a fork needs it, it will still be there.

**Comment by vankasteelj** [comment]
keeping in mind we're talking about _reducing the feature's list_ is important, imo

**Comment by ZakariaRidouh** [comment]
Hmm, looking at what @vankasteelj is saying about removing it becoming one less feature, I was thinking about everyone's ideas about if I should rewrite the issues.js feature with Github (https://www.npmjs.com/package/github)

**Comment by xaiki** [comment]
@ZakariaRidouh that would be very welcome.
