### ISSUE TITLE
Changelog out of date

### ISSUE THREAD

**Issue by metteemo** [butterproject/butter-desktop#403]
The current CHANGELOG.md is a bit out of date:

https://github.com/butterproject/butter-desktop/blob/master/CHANGELOG.md

The people who've contributed to the project might want to insert a couple of bullet points about what was changed/fixed.

**Comment by vankasteelj** [comment]
yes, but changelog is updated on release. That being said, you can draft some points if you want. What I would do is look at the commit list (since 0.3.8 latest release) and go up from there, writing down each "major" change

**Comment by Lionqueen94** [comment]
Then how come that I have 0.3.9-0 "There's nothing on TV" Beta - (80e3fc19) as version? It is not in the changelog...

**Comment by streger** [comment]
Our open source and content license free Butter Project has nothing to do with Popcorn Time that you mentioned. It seems that they have decided to fork our project and to build some software with it. You should probably go to their place and say something about it.

**Comment by Lionqueen94** [comment]
Yeah I just noticed that it were 2 different github projects. But it says Butter project in the app so they have copied this project entirely so it seems.

**Comment by streger** [comment]
Yeah, probably some leftovers from forking our project. Anyway thank you for making a note about this.

**Comment by Lionqueen94** [comment]
https://blog.popcorntime.sh/official-statement/
I still do not understand what happened to popcorntime over the years exactly.
But I assume that that version is okay to have and free from malware.

**Comment by streger** [comment]
You can read a lot about it starting from wiki page...
Anyway, keep your security on standard and you should be good. It seems that they have automatic builds from GitHub so you can check their code for anything malicious, so nothing out from that should end up in binaries.

**Comment by Lionqueen94** [comment]
I am on Linux so I don't really worry about security, but I rather support and use an app that is fully safe and genuine than one like Time4popcorn for example.
Thanks for your responses!

**Comment by vankasteelj** [comment]
In theory, their code is clean, apart maybe if they gather IP-based information on the API they use (wouldn't change from what any website can do). The best way to make sure you have a clean copy is to build yourself (although imo you can have trust... IMO! I haven't checked everything^^), it's somewhat straightforward and shoulnd't take you longer than 10min if you know what you're doing and maybe an hour (read docs, download/install tools, etc) if you don't know anything about building software.

That being said, if you want to contribute to butter, making the changelog is one way of doing so, but you have to understand the source code (on surface at least) to understand what commit changed what in the app.

At some point, I'll be doing it myself anyway, I just don't see the point yet as we're still working on the code and not releasing an app. But I suggest we leave this ticket open because it's something we'll eventually will need to do.
