### ISSUE TITLE
How does search work?

### ISSUE THREAD

**Issue by amilajack** [butterproject/butter-desktop#404]
How does the search functionality work? I've gone to [trakt.tv](trakt.tv) and when I search there, it gives me a very different list of movies than the butter desktop app does. Also when I use the trakt.search() method from the [node trakt.tv api](https://github.com/vankasteelj/trakt.tv), I get the same results that I got from [trakt.tv](trakt.tv). 

Basically, the search results for the PCT desktop app are different from the search results of [trakt.tv](trakt.tv) or the [trakt.tv node api](https://github.com/vankasteelj/trakt.tv)

**Comment by streger** [comment]
This is Butter, please put all your PCT questions on their Issues list (you can find them on GitHub). They have forked our project and they use it for totally different thing than Butter Project idea is. 

Anyway, trakt.tv and internal app search have nothing in common since they both depend on totally different APIs (databases) that most definitely aren't 100% (not even close) exact.

**Comment by amilajack** [comment]
I see. How can I access the database that the internal app search uses?

**Comment by streger** [comment]
Depends on what access do you mean. To get better understanding of how Butter works you can go through our short docs(wikis) and even better go deep in code.

**Comment by amilajack** [comment]
By search I mean the functionality for when you click the search bar:

![screen shot 2016-05-28 at 6 08 37 pm](https://cloud.githubusercontent.com/assets/6374832/15630812/3c86d466-24ff-11e6-9a43-ac7d94fd8d26.png)

I've tried digging into the source and all I seem to have come across is the trakt.tv provider.

**Comment by streger** [comment]
Well, this is a bigger discussion for some other than me, but let me try to keep it simple.
When you do search in app, first it depends where are you searching in (...any provider like our copyright free indie section). When there and you type your search input you're actually searching online database that will return you through the that section API a list of results that configurally give you those results. 
Aside from that (that has nothing to do with that) there is internal local app (on your pc) database that takes care of favorites, watched items (even if not connected to trakt.tv), your settings and similar stuff.

That why you haven't come across most other databases. Because, you're actually when searching any time requesting online search results from some servers that don't depend directly on Butter but are just available for Butter in nice interface to keep those results for our liking.

**Comment by amilajack** [comment]
Sorry for not clarifying. I meant to ask the question with respect to only the movies section (instead of shows, indie, etc).

I think I understand to some extend. So butter-desktop is actually searching "some servers that don't depend directly on Butter". I'm assuming that this includes other providers other than trakt.tv. What are the servers that butter-desktop uses to search? Also, is it possible if I can query them myself so that I can contribute to the project. Thanks!

**Comment by streger** [comment]
This is why I was speaking only generally about it. Butter doesn't have Movies section. You should've stick to my first answer here. Again...find PCT GitHub (https://github.com/popcorn-official/) and ask them about it (or go through their code and find what servers they depend on and query 'em how ever you feel like).

**Comment by amilajack** [comment]
Thanks for the help. And another question: do you know why the [butter forum](http://discuss.butterproject.org/) is down? I've been checking periodically for the last few weeks and it hasn't been up.

**Comment by streger** [comment]
You'll have news about forum soon. I'm currently on it :(

**Comment by ZakariaRidouh** [comment]
CC @xaiki @vankasteelj

**Comment by vankasteelj** [comment]
The search is depending on what is called a "content provider", for example in Butter, the providers are (among other) Vodo, Youtube, CCC and Internet Archive. They are 3rd-party databases sending content for the app. Trakt is a metadata provider, it doesn't give any content except the per-user data, some posters, synopsises etc. 

When you search, what it does is basically contacting the 3rd party database, asking "hey I'm looking for <searchterms>", and that database answers with a list of results. 
The app itself doesn't have any content, it's all about gathering video content from external sources, mix it with metadata from other external sources, display it nicely, and play the video content when the user asks to. 

By default (idk if pct kepts things that way), when you hover with your mouse the tab name (here you said: "movies"), it should display the content provider name(s). That's where the search will go ask.

Trakt is everywhere because its deeply intergrated within the application, and it's used for 2 things: grabbing metadata, but also keeping the users watchlist synced with their trakt account.

**Comment by xaiki** [comment]
tecnically search calls into fetch https://github.com/butterproviders/butter-provider#fetch-object-filters---promise-object in all providers for that tab with a keyword argument.
