### ISSUE TITLE
RGB output color range incorrect in Butter player

### ISSUE THREAD

**Issue by AlexFolland** [butterproject/butter-desktop#409]
The YUV -> RGB conversion output seems to be limited range (16-235), and I can't find an option to force full range (0-255) output.  This makes movies look relatively washed out.

Streaming to MPC-HC, I can work around this by using LAV Video Decoder configured correctly with full range output forced, as can be seen in this screenshot of its settings: http://lex.clansfx.co.uk/dump/c3e5872e01703a3624f788a59ca81936/000005C7.png

I would like to use the internal player due to its ability to stream subtitles.  I'm not sure if no subtitles showing up when streaming to MPC-HC is a bug or not.  For now, I'm streaming to MPC-HC and grabbing external subtitles.

**Comment by vankasteelj** [comment]
You should report this issue to Video.JS (but it's most likely you need to report that issue to node-webkit, maybe even to Chromium, or maybe even to W3C). We don't force a color range and just use what we are given, we have absolutely no control over it.

**Comment by AlexFolland** [comment]
Why close it if the issue isn't fixed?  It still affects this project in a major way, even if it should be reported upstream.

**Comment by vankasteelj** [comment]
We are not going to fix this issue, so why leave a ticket opened that nobody will ever fix? Our plans are to move on to webchimera at some point, https://github.com/butterproject/butter-desktop/issues/344 

Get my point : if you internet is broken because your ISP has trouble, you don't open a ticket on Facebook saying "i cant connect anymore" ^^ See the idea ? :p

**Comment by AlexFolland** [comment]
The way to fix the issue is to have someone report upstream, though.  Nobody will do that if the ticket is just closed.
