### ISSUE TITLE
Needs new Airplay library for Apple TV 4 and subtitle support

### ISSUE THREAD

**Issue by aitte2** [butterproject/butter-desktop#434]
The airplay module in Butter is very, very bare-bones:
src/app/lib/device/airplay.js
(no subtitles, no scrubbing support, etc)

I can see that Butter is currently using "airplay-js":
https://github.com/guerrerocarlos/node-airplay-js

This "airplay-js" library cannot find my AppleTV4, and others are saying that Butter/PT has never been reliable at Airplay. The library doesn't seem very good. It has lots of unanswered, years-old tickets about being unable to find devices.

Here are some potential replacement options:
https://www.npmjs.com/browse/keyword/airplay

Either way, please keep this ticket open. The current airplay library in Butter is awful and will sooner or later need replacing or patching, with something reliable at finding devices.

**Comment by amilajack** [comment]
`zfkun/node-airplay` relies on a global installation of ffmpeg so I dont think it would be considered. `benvanik/node-airplay` seems like the better choice.

**Comment by aitte2** [comment]
@amilajack I had a look at the NPM airplay list, and that @watson guy is super prolific, documenting every AirPlay variant and creating libraries for everything. A true AirPlay genius. His latest release was 4 months ago. And he seems entirely JS-based (no native code), by implementing mDNS and stuff in JS. He even wrote "airharvest" to check for differences in AirPlay versions, so he seems very dedicated to doing the job right!

He has a couple of things of great interest:

https://www.npmjs.com/package/airplay-protocol (a complete implementation of speaking to an AirPlay device)
https://www.npmjs.com/package/bonjour (a bonjour/mDNS implementation in JS, for finding AirPlay devices)

And, he has a complete implementation of a program that finds an AirPlay device and streams to it:
https://www.npmjs.com/package/airplayer
(that code could be hacked apart to build those functions into Butter).

The airplayer code is very simple and uses the bonjour and airplay-protocol packages:
https://github.com/watson/airplayer

My vote is for @watson to jump on board in this discussion and explain his projects.

**Comment by amilajack** [comment]
@aitte2 Do you have an airplay device to test on?

**Comment by aitte2** [comment]
@amilajack I have an Apple TV 4. I'll get the airplayer package and see how it works out.

**Comment by amilajack** [comment]
Great! Also I updated my comment ^

**Comment by aitte2** [comment]
@amilajack Nice! I just noticed that the "airplayer" package is both a CLI app and a programming module. Check the small code example at the top: https://www.npmjs.com/package/airplayer

The "list" object is the bonjour discovery object, and the "player" object corresponds to airplay-protocol. So no need to rip apart "airplayer". Instead, we can just depend on "airplayer" and let it wrap the bonjour and airplay-protocol details if they ever change in the future.

So Butter just needs to do this:

```
var airplayer = require('airplayer')
var airplayBonjourDiscovery = airplayer()

airplayBonjourDiscovery.on('update', function (player) {
    console.log('Found new AirPlay device:', player.name)
    // now just use the "airplay-protocol" player object, such as: player.play(url)
})
```

So I tried the code above, and this is the result:
"Found new AirPlay device: Apple TV Bubbles"

That's better than Butter/PT ever did for me with the old libraries! Now on to the streaming test... I'll get a video file and try it.

**Comment by aitte2** [comment]
Wow! I am streaming the "I Am Legend" 1080p trailer to my Apple TV! I can even pause and scrub on the Apple TV to control the playback via the Apple remote control!

This library kicks ass. @watson you are a genius.

**Comment by amilajack** [comment]
Sounds good! Also what i love about this module is that it has tests. Don't think i've seen other casting modules with tests. Also thinking of making a PR to add Appveyor support (for windows).

**Comment by amilajack** [comment]
Also on a side note, are you willing to test an experimental pct client of mine:
http://github.com/amilajack/popcorn-desktop-experimental

**Comment by aitte2** [comment]
@amilajack Sorry I can't try popcorntime due to legality issues with my ISP.

I am working on implementing @watson's airplay-protocol and bonjour modules in butter-desktop. I noticed that the "airplayer" app was a bit of a "too thick" wrapper over what we need, because it obscures the bonjour discovery and auto-deletes devices when they stop streaming, etc. So I am using the modules directly instead.

**Comment by losh11** [comment]
+1

Older versions of popcorn-time, every 1 out of 20 sessions would have issues with AirPlay streaming where the session would time out in the middle of streaming. This would mean that the user would not be able to scrub back to the point where the session abruptly ended - using the remote to forward the streamed video would sometimes slowly forward (at x1) when it should forward at max speed.

I would be willing to try your client @amilajack but I don't have an Apple TV4, but I do have a TV3. Let me know if I can help in testing.

**Comment by aitte2** [comment]
Alright... I've used the new libraries to massively improve AirPlay on Butter/PT, and I can now detect the AirPlay devices perfectly, and can start streaming to them. *But* there are other deep issues in Butter/PT. For that reason, I'll contribute the finished code as-is, as well as a list of what needs to be done, so that others can carry on the work:


**Step 1:** Edit "package.json" to swap to the new library.

Remove the awful "airplay-js" as a dependency.
Add the following dependencies instead:
```
"airplay-protocol": "^2.0.2",
"bonjour": "^3.3.1",
```

**Step 2:** Replace all contents of "src/app/lib/device/airplay.js" with the following code instead. This new code is feature-complete and is ready to be used. It handles all functions that the old code tried to handle, but this one actually *works*.
Backup link: http://pastebin.com/Et6xmaLw
```
(function (App) {
    'use strict';

    var Bonjour = require('bonjour'),
        AirPlayProtocol = require('airplay-protocol');

    var bonjourBrowser = new Bonjour(),
        collection = App.Device.Collection;

    var makeID = function (bonjourService) {
        // strong ID since there can only be 1 bonjour service per host+port
        var uniqueDeviceId = bonjourService.host + '_' + bonjourService.port;
        return 'airplay-' + Common.md5(uniqueDeviceId);
    };

    var AirPlay = App.Device.Generic.extend({
        defaults: {
            type: 'airplay',
            typeFamily: 'external'
        },

        _makeID: makeID,

        initialize: function (attrs) {
            this.device = attrs.device;
            this.attributes.id = this._makeID(this.device.service);
            this.attributes.name = this.device.service.name;
            this.attributes.address = this.device.service.host;
        },

        play: function (streamModel) {
            var self = this;
            var url = streamModel.get('src');
            this.device.player.play(url, function (err, res, body) {
                if (err) {
                    // FIXME: do something on failure to play
                }
            });
        },

        stop: function () {
            this.device.player.stop();
        }
    });

    // start scanning for AirPlay services and their status changes
    win.info('Scanning: Local Network for AirPlay servers');
    var airplayBrowser = bonjourBrowser.find({ type: 'airplay' });

    // AirPlay service answered our search query or broadcasts going up
    airplayBrowser.on('up', function (service) {
        var model = collection.get({
            id: makeID(service)
        });
        if (!model) {
            // we don't already know about this host+port combo, so add it!
            var device = {
                service: service,
                player: new AirPlayProtocol(service.host, service.port)
            };

            collection.add(new AirPlay({
                device: device
            }));
        }
    });

    // AirPlay service broadcasts going down
    // this usually only happens when turning off AirPlay in the ATV settings
    airplayBrowser.on('down', function (service) {
        var model = collection.get({
            id: makeID(service)
        });
        if (model) {
            model.destroy();
        }
    });

    App.Device.AirPlay = AirPlay;
})(window.App);
```


**Step 3:** Now, about those deep problems in Butter/PT...

3a: Butter defaults to using the IPv6 address as the streaming hostname:
`""[%cINFO%c] Available IPs: [\"fe80::6233:4bff:fe11:a4de\",\"10.0.1.167\"]""`
It picks the "fe80" name. It must always pick an IPv4 address if one is available. My AppleTV4 refuses to connect if I am on IPv6. I had to manually run "networksetup -setv6on Wi-Fi" to turn off IPv6 to get Butter to advertise a IPv4 streaming URL.

3b: Even on IPv4, something is preventing streaming from actually starting on the AppleTV4. I can see that the new libraries work perfectly (I tried them standalone, without Butter earlier, and was able to stream a 1080p movie trailer perfectly). So the problem is in Butter. The AppleTV4 tries to connect to the stream (i.e. "http://10.0.1.167:40830/") and the TV screen flashes black for half a second, but then it disconnects from the stream. That's some problem in Butter itself.

Possible reasons for the Butter problem (which would have happened with the old AirPlay library too): 1. Perhaps we need to give a filename, like "http://10.0.1.167:40830/stream.m4v"? 2. Perhaps we aren't sending proper MIME headers from Butter's media server.

**Step 4:** After doing all of the above (switching to the new libraries with my code, making Butter select IPv4 by default, and fixing the MIME/filename issues that are preventing a stream connection), there's just one thing left to do: Read the airplay-protocol API (https://github.com/watson/airplay-protocol) and implement more of the streaming functions. I would have done all of that but since Butter's streaming server isn't working, I had to stop here.

**Comment by aitte2** [comment]
So in short: Use the new libraries and the new code I posted. The new code I provided for Butter perfectly discovers AirPlay devices using Bonjour (whereas the old "airplay-js" didn't see them at all!), and it perfectly sends the player play/stop commands.

The fact that streaming just flashes for half a second and then aborts on the AppleTV is a SEPARATE issue, which will require fixes to Butter's streaming media server itself. I have confirmed that the new airplay+bonjour libraries work perfectly when used outside of Butter. The Butter streaming server is the next problem to tackle. And I can't help with that since I'm not deeply involved enough in this project to know where to begin. Good luck. :)

**Comment by aitte2** [comment]
@losh11 Feel free to try the new code above. The only thing that it alters is the Bonjour AirPlay device discovery (it's a very good Bonjour mDNS implementation which now actually works and finds the AirPlay devices), as well as changing the way it sends the AirPlay "start streaming a URL" command. Both are much more robust now.

I've independently verified that the "start streaming a URL" command works and was able to stream (via this code: https://github.com/watson/airplayer/blob/master/bin.js), so the remaining problems are in Butter. The IPv6 issue and the lack of proper streaming server headers.

**Comment by aitte2** [comment]
At least the ball is rolling now! Hopefully someone picks it up. ;) Take care!

**Comment by aitte2** [comment]
Oh and @watson, thanks a lot again for your wonderful libraries. Perhaps you can help the Butter project debug why their HTTP media server isn't compatible with the AppleTV4? Your own "airplayer" server project works perfectly. And perhaps you know how to send the "vtt" subtitle stream command to the AirPlay server? If that could be achieved with/added to your library, we'll even have subtitle support. :)

**Comment by amilajack** [comment]
@losh11 Great! We have a [getting started guide](https://github.com/amilajack/popcorn-time-desktop#getting-started). If you dont want to install and build you can always go straight to the [releases](https://github.com/amilajack/popcorn-time-desktop/releases/tag/v0.0.5-alpha).

**Comment by watson** [comment]
Hi guys, thanks for considering using my airplay modules - much appreciated!

I'd love to help out if possible, so if any issues arise (bugs, missing features etc), please reach out 😃

**Comment by xaiki** [comment]
hey @aitte2 your work is very apreciated, whenever you feel like it please send us a PR, for your IP issues it looks like the solution should be that the airplay2 module should have an option to list v4 addresses first (instead of forcing all of butter to use v4 by default), @watson what's your take on this ?

**Comment by watson** [comment]
@xaiki It's been a few months since I played with this my self, so I can't remember all the details off the top of my head. But I just had quick look at the code posted above and it seems ok.

Regarding subtitles: Currently the airplayer module streams raw video to the Apple TV and implements seeking using HTTP range queries. As far as I know, the only way to support subtitles is to package the video inside HLS, which is a bit more work. I haven't looked into VTT, but I'd imagine it would still require HLS as the wrapper.

I'll see if I have time to look into adding support for it soon.

**Comment by xaiki** [comment]
ok, i see, the issue is a lot of code added by @ddaf in `lib/device/generic.js` that will mangle your ips, and try to find the 'best fiting one'... you can correct that again into your play function, but it probably should go onto an device method so that you can override the selection.

**Comment by watson** [comment]
I had a look at adding subtitles yesterday, and this is my findings to far:

## Adding subtitles to an mp4 container 

It seems to be possible to add subtitles to mp4 containers without using HLS/m3u8. The mp4 container format consists of "boxes" (previously known as atoms). One of these boxes can contain subtitles.

To take an external subtitles file and embed it into an mp4 container, once would need to first decode the container and output (encode) a new container with the subtitles box added in.

I've been trying to use the [mp4-stream](https://github.com/mafintosh/mp4-stream) module to achieve this, but so far without any luck.

## Wrapping inside an m3u8 playlist

The most used approach is to wrap the movie in an m3u8 playlist. This allows you to add multiple bitrates of the same movie, separate audio-tracks and multiple subtitle tracks.

The downside of this approach is that it seems to require splitting up the file in multiple chunks of say 30 seconds each. This is problematic, because you need to parse the video to chop it up into these chunks. Most implementations uses ffmpeg to do this, but ffmpeg normally needs to be compiled locally on the users computer which makes this a hassle.

Also, as far as I know, m3u8 requires each segment to be mpeg2 - so mpeg4 videos needs to be converted.

In iOS 10 / macOS 10.12 / tvOS 10 an later, fMPG and range queries is supported in m3u8 which (i think) means that we don't need to parse the video file to split it into 30 second segments and that we don't need to convert it to mpeg2 - but I have not validated any of this.

**Comment by SteveJobzniak** [comment]
Pull request for aitte's changes, since he said he didn't have any more time and asked others to carry on his work. I've verified his changes and created a PR:

https://github.com/butterproject/butter-desktop/pull/437

And he's right, the current Butter streaming server doesn't yet support the Apple TV 4. But at least it _finds_ it now and attempts to start streaming!

@watson Wow, you really followed through on your promise to research AirPlay subtitles. Thank you! <3

Out of those options, rewrapping in MP4 on-the-fly looks like the least CPU intensive method. Current M3U8's require converting to MPEG2-TS and splitting into 30 second chunks.

I haven't heard of modern M3U8 players supporting non-split MP4s and Range queries instead, but even if that's true it would still mean we need MP4 files.

So it looks like the best method is:
- Create a dummy MP4 container with one or more subtitle atoms at the start.
- Then re-wrap the video and audio data from the older container into MP4 on the fly.

@xaiki I'm not too familiar with Butter, but maybe it already contains ffmpeg? If so, perhaps we can force ffmpeg to add a subtitle stream to the output.

Also: I see what you mean about "generic.js" trying to find the closest IP. Something would need to be changed to make it prefer IPv4 for AirPlay. I can't promise that I'll look at it. I just wanted to submit the PR to see the AirPlay changes get added, but perhaps I'll do further work too. :)

**Comment by xaiki** [comment]
@SteveJobzniak we don't ship ffmpeg, will comment on your PR, thanks for picking this up !

**Comment by vankasteelj** [comment]
https://github.com/butterproject/butter-desktop/pull/466/files
