### ISSUE TITLE
Switching to NOTO sans ?

### ISSUE THREAD

**Issue by vankasteelj** [butterproject/butter-desktop#444]
Google just released NOTO, that I've personnaly been waiting for. Turns out it's elegant, on top of being practical. Should we switch ?

See https://www.google.com/get/noto/

**Comment by streger** [comment]
That would be nice to have, practical-wise. 

How would we incorporate all the fonts for particular languages? Have them all included in our installation? That could be a huge increase in size because of it, isn't that bad?

Or did you just meant to use just one, like Noto Sans? I definitely agree on that one.

**Comment by vankasteelj** [comment]
Yeah, NOTO Sans is 581 languages, "close enough" might I say

**Comment by xaiki** [comment]
i'm a bit worried about the resulting size increase, how big will noto be for us ? currently we don't look good in languages when there is no good unifont support on the platform. can we try to get it in and see what's the cost ?

**Comment by vankasteelj** [comment]
at first sight we should be about 150kb less than right now.

**Comment by xaiki** [comment]
dropped in favour of dosis
