### ISSUE TITLE
Custom protocol

### ISSUE THREAD

**Issue by iadj** [butterproject/butter-desktop#54]
I'm a big fan of launching an app from the browser.
Being able to stream in the Butter client by opening an anchor like `butter://[magnet]` would be super cool!

**Comment by ayhankuru** [comment]
nice feature :+1:

**Comment by paulhobbel** [comment]
Nice feature should get the enhancement tag

**Comment by streger** [comment]
It should already work, at least it did before. But like normal torrent client to pick up the magnet protocol from browser and start it. Also with .torrent file to set as default application.

**Comment by iadj** [comment]
@streger A lot of people (me included) have the `magnet://` protocol reserved for their standard Torrent clients. A custom protocol would allow us to start streams in 1 click without having to change applications every time when clicking the anchor.

**Comment by streger** [comment]
...and you would need to convince people to include new protocol on their websites or make an browser extension that would inject it on pages when magnet link is detected.

**Comment by iadj** [comment]
@streger You don't have to convince anyone to use a new protocol. The app could support both `magnet://` and `butter://` and people can choose to use or integrate the app however they want :)

**Comment by ironicnet** [comment]
Creating another protocol just for reading a magnet link when you have "magnet" for that it's like adding more noise. It's like the inverse of this: https://xkcd.com/927/

**Comment by prcastro** [comment]
I believe we should stick to the `magnet` protocol

**Comment by douglascamata** [comment]
I like @iadj's solution. It isn't noisy and ultimately comes down to the user's preference. Making Butter work with the `magnet` protocol would be annoying, because most of the users don't always want to open torrents with Butter if they are not videos. Btw, creating a Butter browser extension to detect the magnet link and allow users to click to extension's icon to start streaming immediately seems reasonable for me.

**Comment by hmarafi** [comment]
@iadj Idea is great, you can use both, Butter + Magnet.

**Comment by physiii** [comment]
We could use a torrent client and stick with magnets then have butter decide to stream or download. Eventually I think we will want to stream straight from the browser using something like webtorrent: https://github.com/feross/webtorrent

**Comment by ironicnet** [comment]
I believe that if we are going to add another protocol and try to make it
an standard. We should go for a more "generic" term... like "Play" or
something like that. That way if someone forks this project or wants to use
another app for streaming, they could use the same sites.
I still prefer to use the _magnet_ protocol, but if not let the user decide
which kind of application to use when clicking in a magnet/torrent...



On Tue, Oct 27, 2015 at 3:38 PM, physiii <notifications@github.com> wrote:

> We could use a torrent client and stick with magnets then have butter
> decide to stream or download. Eventually I think we will want to stream
> straight from the browser using something like webtorrent:
> https://github.com/feross/webtorrent
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/butterproject/butter/issues/54#issuecomment-151604254>
> .
>



-- 
______
Ezequiel Calderara,

* .Net Developer. Http://www.ironicnet.com <Http://www.ironicnet.com> |
ezechico@gmail.com <ezechico@gmail.com>*

**Comment by JohnDoee** [comment]
There's room for a way to link external media players with e.g. webbrowsers.

Currently, there's no smart way to play an HTTP link in VLC without some copy/paste stuff.

What I have in mind is something like stream://. The problem is that it'd lose its original protocol meaning, i.e. nobody knows how to fetch the stream. This can be solved by taking a lesson from git urls and throw in a + and add the original protocol, e.g. stream+http:// where http is the protocol used to get the streamable item.

A concrete example:

The initial link clicked is: stream+magnet:?xt=urn:btih:5dee65101db281ac9c46344cd6b175cdcad53426&dn=download
The torrent is downloaded by butter and then either played back or another link is shown. stream+http://127.0.0.1:21584/some-item.mp4 - The new link can be played in an external player like VLC.

The only thing required is a small program to handle the redirection of links to applications and it will be generic enough to allow others to use it.

**Comment by douglascamata** [comment]
@JohnDoee take my +1

**Comment by ironicnet** [comment]
@JohnDoee That's kinda what i was talking about. That will allow the protocol to be compatible with more programs!

If someone is planning to create such app, post the link here

**Comment by JohnDoee** [comment]
I was unable to find anyone else solving this problem and therefore whipped up a small solution to this that should be good to go this weekend.

One big issue remains, given a multi-file torrent, how do I tell butter which file I want to stream ? Judging by https://github.com/butterproject/butter-desktop/blob/master/src/app/app.js#L619-L623 it does not seem like it's supported. Should I just open a ticket regarding specifying file with command-line arguments ?

What I'd want is something like this:

    butter.exe http://example.com/somefile.torrent path/to/file.mp4

or

    butter.exe --file=path/to/file.mp4 http://example.com/somefile.torrent

**Comment by JohnDoee** [comment]
So, I actually made this long ago and can be found here: http://streamprotocol.tidalstream.org/ - it's a way to get data from websites into media players right now. There's a few GreaseMonkey scripts to show how to integrate it into websites.

I am both waiting for an actual Butter Project release (need to see how to auto-detect it) and hopefully a way to handle multi-file torrents.

**Comment by streger** [comment]
Link to connect this to more general discussion about this:
https://github.com/feross/webtorrent-desktop/issues/83

**Comment by prcastro** [comment]
I think we should stick to WebTorrent decision to use `stream-magnet` protocol afterall

**Comment by xaiki** [comment]
yes it's tracket to #422
