### ISSUE TITLE
item rows not justified

### ISSUE THREAD

**Issue by vankasteelj** [butterproject/butter-desktop#562]
A picture is worth a thousand words:

![croquis](https://cloud.githubusercontent.com/assets/12599850/21481552/42fbd3e4-cb69-11e6-896f-6391b06efcf0.png)

**Comment by xaiki** [comment]
@btzr-io and /me have been looking into this, it's due to use `justify-content: flex-start, the good thing about that is that it removes ugly ghost elements, the bad thing is that if we set it to any other value like `space-between` the last row turns to shit.

we've tried using a `:last-child` or a `::after` element to eat up the space, but it then kills the flexible margins between elemnts in the last row.

**Comment by vankasteelj** [comment]
maybe try hacking last row? Like : 

1) make complete rows justified
2) detect last row, use row-1 spacing, apply it to last row

💯/💯

**Comment by xaiki** [comment]
i don't know how to detect 'last-row' in flex

**Comment by vankasteelj** [comment]
it existed in the base code, did you also kill the part of itemsInRow and isLastRow?
