### ISSUE TITLE
Add the option to set up a default video quality on "Settings"

### ISSUE THREAD

**Issue by popcornenthusiast** [butterproject/butter-desktop#569]
Make possible to set up a default video quality on "Settings". If the quality set isn't available for a content then select the quality just below it before playing OR the one right above the quality set if there isn't one below it. If the quality set on settings is available but the torrent for it has a medium health or lower, then check the quality/torrent just below it. If it's better, then use it instead of the quality set. If it has the same health or worse, keep with the quality set.

This setting should be used to set the default quality when opening Butter and when playing from a playlist (See #570 ). This setting should not override the user setting on details page.

**Comment by xaiki** [comment]
you have an option to list only movies in a certain quality.
we don't want to be a video player, i'm very not convinced we'll do the playlist thing, so i'm going to close this.

**Comment by popcornenthusiast** [comment]
@xaiki 

> you have an option to list only movies in a certain quality.

Which doesn't works when binge-watching a tv show (using "Next episode in series"), neither makes sense when watching YouTube. Edited the feature description for clarification on this matter

> we don't want to be a video player

From an user experience point of view that's just impossible. For the user there is no such things as "releases", "torrent availability", "api", "availability through the api" and "torrent health". Or the movie/tv show episode is available or it isn't, or it plays or it doesn't. The reasons don't matter. A feature like that would make for a smoother "streaming" and, like I said, the playlists are only one use for this feature.

**Comment by xaiki** [comment]
@abadfederico @btzr-io you do design and UX please cut on this issue.

**Comment by vankasteelj** [comment]
I'm somewhat against this. I mean, not the idea itself, but the setting itself. 

I already designed a "smart setting" a while ago. ofc with multi sources and play next it isn't working anymore, but the idea is basically, let the user select a quality, and consider it is the chosen quality. Everything is done internally, invisible to the user. It would work like this:
1) default quality is "highest available". The user then switches to 480p, for example.
2) internally, we record the choice for 480p. We try to match that in the future, by selecting the closest. For example, if there is only 720 and 1080 available, 720 is chosen, because it's the closest to 480. 

in code, it could be some wrapper in settings.js : Settings.getUserQuality([available qualities]) would return the best matching quality. Internal settings would be:
- default: the highest available
- user selected: 480, 720, 1080
