### ISSUE TITLE
New Update is not working. Low quality 480P is not loading and following errors shwing as in screenshot

### ISSUE THREAD

**Issue by iMansoorAliKhan** [butterproject/butter-desktop#725]
![image](https://user-images.githubusercontent.com/11312949/97781844-cdbeea80-1baf-11eb-92ea-15b73511e028.png)

Not downloading even when there were 30+ seeds active.
![image](https://user-images.githubusercontent.com/11312949/97781862-eaf3b900-1baf-11eb-8989-73350206d680.png)

Log of console attached for your kind reference
[hecfofbbdfadifpemejbbdcjmfmboohj-1604154852218.log](https://github.com/butterproject/butter-desktop/files/5469245/hecfofbbdfadifpemejbbdcjmfmboohj-1604154852218.log)

**Comment by xaiki** [comment]
it looks like your bug affects popcorntime not butter.

**Comment by iMansoorAliKhan** [comment]
I have downloaded this from this GIT REPO, that's  not default popcorntime but this butter.

![image](https://user-images.githubusercontent.com/11312949/97794939-09929800-1c22-11eb-8622-41bb2c81a300.png)

**Comment by iMansoorAliKhan** [comment]
in my popcorntime its this

![image](https://user-images.githubusercontent.com/11312949/97795024-1cf23300-1c23-11eb-9d13-0fb6f9b11a60.png)


how this is not butter??

**Comment by xaiki** [comment]
Popcorn Time used to be a clean fork of butter, but with different providers packed in.
your issue seems to be related to a format the popcorn-time providers are giving you.

that said as this project hasn't been active for a long time, you should consider PopcornTime as your prime source of developement, i hear they are still maintaing it very well.
